#!/usr/bin/env python3
# extract_sow_items.py - pull the item/gear catalog out of the extracted game.gamedb (GADB).
#
# Pipeline to get game.gamedb (once):
#   QuickBMS: quickbms_4gb_files.exe -o -f "*game.gamedb" shadow_of_mordor.bms Patch_02.arch06 <out>
#   (QuickBMS Oodle-decompresses the ~888 chunks -> database\game\game.gamedb, ~55 MB)
#
# game.gamedb format: magic 'GADB', a header of section offsets, then inline NUL-separated
# type names + record names + binary field data. We don't need the full record parser to build
# the catalog: the record NAMES are ASCII and follow strict conventions, so we scan for them.
#
#   python extract_sow_items.py <game.gamedb> [outdir]
import sys, os, re, json, collections

def ascii_strings(data, minlen=3):
    # yield (offset, string) for runs of printable ASCII
    out, start, cur = [], None, []
    for i, b in enumerate(data):
        if 0x20 <= b < 0x7f:
            if start is None: start = i
            cur.append(b)
        else:
            if start is not None and len(cur) >= minlen:
                out.append((start, bytes(cur).decode('ascii')))
            start, cur = None, []
    if start is not None and len(cur) >= minlen:
        out.append((start, bytes(cur).decode('ascii')))
    return out

# ---- sophisticated grouping: gear -> slot -> set -> tier, everything sorted deterministically ----

# weapon-type token -> (slot sort key, slot display name). Faction/tint gear folds into a slot.
def slot_of(wtype):
    w = wtype
    def has(*xs): return any(x in w for x in xs)
    if has('Sword'):  return (1, 'Sword')
    if has('Dagger'): return (2, 'Dagger')
    if has('Bow'):    return (3, 'Bow')
    if has('Armor'):  return (4, 'Armor')
    if has('Cape', 'Cloak'): return (5, 'Cloak')
    if has('Talion'): return (6, 'Talion')
    return (9, wtype)

# set / theme -> (sort key, display). Rarity buckets first, then named legendary sets, then skins.
RARITY = {'1Common': 0, '2Uncommon': 1, '3Rare': 2, '4Epic': 3, '5Legendary': 4}
LEGEND_SETS = ['Celebrimbor', 'Vendetta', 'Dark', 'Feral', 'Machine', 'Marauder', 'Mystic',
               'Outlaw', 'Ringwraith', 'Slaughter', 'Terror', 'Warmonger', 'Ringcraft']
def set_of(theme, wtype):
    if theme in RARITY: return (0, RARITY[theme], theme.lstrip('012345'))
    if theme in LEGEND_SETS: return (1, LEGEND_SETS.index(theme), theme)
    # faction gear carries its faction in the weaponType token (RohanArmor, GondorianCloak, ...)
    for fac in ('Rohan', 'Ranger', 'Numenorean', 'Gondorian'):
        if wtype.startswith(fac): return (2, 0, fac)
    if theme.startswith('Tint'): return (3, int(theme[4:] or 0), 'Skins')
    return (4, 0, theme or '?')

def tier_key(tier):
    return int(tier[1:]) if tier.startswith('T') and tier[1:].isdigit() else 99

def write_mod_catalog(parsed, cats):
    import os
    root = os.path.dirname(os.path.abspath(__file__))
    mod = os.path.join(root, '..', 'mods', 'InventoryEditor')
    os.makedirs(mod, exist_ok=True)

    rows = []   # (category, group, subgroup, label, record) fully sorted
    for p in parsed:
        so, slot = slot_of(p['weaponType'])
        s0, s1, setname = set_of(p['theme'], p['weaponType'])
        rows.append(((0, so, s0, s1, setname, tier_key(p['tier']), p['record']),
                     'GEAR', slot, setname, p['tier'] or '-', p['record']))
    catmap = [('RUNE', cats['Rune']), ('RUNEGEM', cats['Runegem']), ('GEM', cats['Gem']),
              ('WEAPON', cats['Weapon']), ('ARMOR', cats['Armor'])]
    for cat, lst in catmap:
        for rec in lst:
            rows.append(((1, cat, rec), cat, cat.title(), '-', '-', rec))
    rows.sort(key=lambda r: r[0])

    # mod-consumable TSV: category<TAB>group<TAB>subgroup<TAB>tier<TAB>record  (loaded at runtime)
    catalog = os.path.join(mod, 'InventoryEditor.catalog')
    with open(catalog, 'w', encoding='utf-8') as f:
        f.write('# SoW item catalog (auto-generated by tools/extract_sow_items.py from game.gamedb)\n')
        f.write('# category\tgroup\tsubgroup\ttier\trecord\n')
        for r in rows:
            f.write('\t'.join([r[1], r[2], r[3], r[4], r[5]]) + '\n')

    # human-readable grouped view
    with open(os.path.join(root, 'sow_catalog', 'catalog.md'), 'w', encoding='utf-8') as f:
        f.write('# Shadow of War — item catalog\n\n')
        cur_cat = cur_grp = cur_sub = None
        for r in rows:
            _, cat, grp, sub, tier, rec = r
            if cat != cur_cat: f.write(f'\n## {cat}\n'); cur_cat, cur_grp, cur_sub = cat, None, None
            if grp != cur_grp: f.write(f'\n### {grp}\n'); cur_grp, cur_sub = grp, None
            if sub != cur_sub: f.write(f'\n**{sub}**\n\n'); cur_sub = sub
            f.write(f'- {rec}' + (f'  ({tier})' if tier not in ('-', '') else '') + '\n')
    print(f'grouped catalog -> {catalog} ({len(rows)} records)')


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else r'C:\dev\quickbms\extract\database\game\game.gamedb'
    outdir = sys.argv[2] if len(sys.argv) > 2 else os.path.dirname(os.path.abspath(__file__)) + r'\sow_catalog'
    os.makedirs(outdir, exist_ok=True)
    data = open(path, 'rb').read()
    assert data[:4] == b'GADB', 'not a GADB file'

    def find(pat):  # byte-regex substring scan (like grep -ao), returns sorted unique strs
        return sorted({m.decode('ascii') for m in re.findall(pat, data)})

    # Gear pieces: GearArt_<Type>_<Theme>_<Tier>  (the equippable gear templates)
    gear = find(rb'GearArt_[A-Za-z0-9_]+')
    parsed = []
    for g in gear:
        parts = g[len('GearArt_'):].split('_')
        wtype = parts[0] if len(parts) > 0 else ''
        theme = parts[1] if len(parts) > 1 else ''
        tier  = parts[2] if len(parts) > 2 else ''
        parsed.append({'record': g, 'weaponType': wtype, 'theme': theme, 'tier': tier})

    # Other item-category records by leading keyword (byte-regex scan)
    cats = collections.OrderedDict()
    for kw in ('Rune', 'Runegem', 'Gem', 'Weapon', 'Armor', 'GearTag'):
        cats[kw] = find(('\\b' + kw + r'[A-Za-z0-9_]{2,}').encode())

    # write catalog
    with open(outdir + r'\gear.json', 'w') as f:
        json.dump(parsed, f, indent=1)
    with open(outdir + r'\gear.txt', 'w') as f:
        for g in gear: f.write(g + '\n')
    for kw, lst in cats.items():
        with open(outdir + '\\' + kw.lower() + '.txt', 'w') as f:
            for s in lst: f.write(s + '\n')

    # ---- sophisticated grouping + sorting, emitted as the InventoryEditor mod's catalog ----
    write_mod_catalog(parsed, cats)

    # summary
    by_type = collections.Counter(p['weaponType'] for p in parsed)
    by_theme = collections.Counter(p['theme'] for p in parsed if p['theme'])
    print(f'game.gamedb: {len(data):,} bytes')
    print(f'GEAR pieces (GearArt_): {len(gear)}')
    print('  by weapon/gear type:', dict(by_type.most_common(12)))
    print('  by theme:', dict(by_theme.most_common(15)))
    for kw, lst in cats.items():
        print(f'{kw}: {len(lst)} records')
    print(f'\nwrote catalog to {outdir}')

if __name__ == '__main__':
    main()
